language: ruby

rvm:
  - 1.9.2

env:
  # Keys for auto-deploy
  global:
    - secure: "HZzwxgt6jnMEZvN1d55GQ1/3FNsjZZi9XoBinZoYt1iBi9UJbetQRJzZnyLR\nBK3rVqGFg5lihGB+o7UC8WEi/rGPSJNc4AU0p83zUoTE07nMIcLIgg0Drebo\nUiTPQqWKaQRrRfe1mcMlcMiR3C8H9LlcJ/yGARtaSto77r9IYDE="

    # Dummy values for Travis CI test environment
    - EIBF_AMAZON_KEY=ABCDEFG1234567890ABC
      EIBF_AMAZON_SECRET=ABCDEFG1234567890ABCDEFG1234567890ABCDEF
      EIBF_AMAZON_TRACKING_ID=tracktracktrack
      EIBF_FEED_PASSWORD=123412341234
      EIBF_FEED_URL=http://www.edbookfest.co.uk/events/feed
      EIBF_FEED_USERNAME=m-ebf-mob
      EIBF_GUARDIAN_API=abcdefghijklmnopqrstuvwx
      EIBF_STOCK_URL=http://online.edbookfest.co.uk/booksales/stock.xml
      EIBF_ITUNES_TDUID=UK0000000
      HTTP_USERNAME=user
      HTTP_PASSWORD=password
      EIBF_GOOGLE_SITE_VERIFICATION=abcdefghijkl

before_install:
  # Install Chrome WebDriver
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sudo ./install_chrome_webdriver

before_script:
  - rake db:migrate

after_success:
  - ruby travis_deployer.rb

notifications:
  email:
    - andrew@ingenerator.com
