require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe FestivalThemesController do

  # This should return the minimal set of attributes required to create a valid
  # FestivalTheme. As you add validations to FestivalTheme, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # FestivalThemesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all festival_themes as @festival_themes" do
      festival_theme = FestivalTheme.create! valid_attributes
      get :index, {}, valid_session
      assigns(:festival_themes).should eq([festival_theme])
    end
  end

  describe "GET show" do
    it "assigns the requested festival_theme as @festival_theme" do
      festival_theme = FestivalTheme.create! valid_attributes
      get :show, {:id => festival_theme.to_param}, valid_session
      assigns(:festival_theme).should eq(festival_theme)
    end
  end

  describe "GET new" do
    it "assigns a new festival_theme as @festival_theme" do
      get :new, {}, valid_session
      assigns(:festival_theme).should be_a_new(FestivalTheme)
    end
  end

  describe "GET edit" do
    it "assigns the requested festival_theme as @festival_theme" do
      festival_theme = FestivalTheme.create! valid_attributes
      get :edit, {:id => festival_theme.to_param}, valid_session
      assigns(:festival_theme).should eq(festival_theme)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new FestivalTheme" do
        expect {
          post :create, {:festival_theme => valid_attributes}, valid_session
        }.to change(FestivalTheme, :count).by(1)
      end

      it "assigns a newly created festival_theme as @festival_theme" do
        post :create, {:festival_theme => valid_attributes}, valid_session
        assigns(:festival_theme).should be_a(FestivalTheme)
        assigns(:festival_theme).should be_persisted
      end

      it "redirects to the created festival_theme" do
        post :create, {:festival_theme => valid_attributes}, valid_session
        response.should redirect_to(FestivalTheme.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved festival_theme as @festival_theme" do
        # Trigger the behavior that occurs when invalid params are submitted
        FestivalTheme.any_instance.stub(:save).and_return(false)
        post :create, {:festival_theme => {}}, valid_session
        assigns(:festival_theme).should be_a_new(FestivalTheme)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        FestivalTheme.any_instance.stub(:save).and_return(false)
        post :create, {:festival_theme => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested festival_theme" do
        festival_theme = FestivalTheme.create! valid_attributes
        # Assuming there are no other festival_themes in the database, this
        # specifies that the FestivalTheme created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        FestivalTheme.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => festival_theme.to_param, :festival_theme => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested festival_theme as @festival_theme" do
        festival_theme = FestivalTheme.create! valid_attributes
        put :update, {:id => festival_theme.to_param, :festival_theme => valid_attributes}, valid_session
        assigns(:festival_theme).should eq(festival_theme)
      end

      it "redirects to the festival_theme" do
        festival_theme = FestivalTheme.create! valid_attributes
        put :update, {:id => festival_theme.to_param, :festival_theme => valid_attributes}, valid_session
        response.should redirect_to(festival_theme)
      end
    end

    describe "with invalid params" do
      it "assigns the festival_theme as @festival_theme" do
        festival_theme = FestivalTheme.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        FestivalTheme.any_instance.stub(:save).and_return(false)
        put :update, {:id => festival_theme.to_param, :festival_theme => {}}, valid_session
        assigns(:festival_theme).should eq(festival_theme)
      end

      it "re-renders the 'edit' template" do
        festival_theme = FestivalTheme.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        FestivalTheme.any_instance.stub(:save).and_return(false)
        put :update, {:id => festival_theme.to_param, :festival_theme => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested festival_theme" do
      festival_theme = FestivalTheme.create! valid_attributes
      expect {
        delete :destroy, {:id => festival_theme.to_param}, valid_session
      }.to change(FestivalTheme, :count).by(-1)
    end

    it "redirects to the festival_themes list" do
      festival_theme = FestivalTheme.create! valid_attributes
      delete :destroy, {:id => festival_theme.to_param}, valid_session
      response.should redirect_to(festival_themes_url)
    end
  end

end
